# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/xlinx-projects/snoop_controller_timer/snoop_controller_timer.srcs/sources_1/bd/scutimer/ip/scutimer_processing_system7_0_0/scutimer_processing_system7_0_0.xci
# IP: The module: 'scutimer_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/xlinx-projects/snoop_controller_timer/snoop_controller_timer.srcs/sources_1/bd/scutimer/ip/scutimer_processing_system7_0_0/scutimer_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'scutimer_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/xlinx-projects/snoop_controller_timer/snoop_controller_timer.srcs/sources_1/bd/scutimer/ip/scutimer_processing_system7_0_0/scutimer_processing_system7_0_0.xci
# IP: The module: 'scutimer_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/xlinx-projects/snoop_controller_timer/snoop_controller_timer.srcs/sources_1/bd/scutimer/ip/scutimer_processing_system7_0_0/scutimer_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'scutimer_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
