# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/accumulator_design/accumulator_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accumulator_design || ORIG_REF_NAME==accumulator_design} -quiet] -quiet

# IP: bd/accumulator_design/ip/accumulator_design_processing_system7_0_0/accumulator_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accumulator_design_processing_system7_0_0 || ORIG_REF_NAME==accumulator_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/accumulator_design/ip/accumulator_design_floating_point_0_0/accumulator_design_floating_point_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accumulator_design_floating_point_0_0 || ORIG_REF_NAME==accumulator_design_floating_point_0_0} -quiet] -quiet

# IP: bd/accumulator_design/ip/accumulator_design_axi_dma_0_0/accumulator_design_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accumulator_design_axi_dma_0_0 || ORIG_REF_NAME==accumulator_design_axi_dma_0_0} -quiet] -quiet

# IP: bd/accumulator_design/ip/accumulator_design_smartconnect_0_0/accumulator_design_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accumulator_design_smartconnect_0_0 || ORIG_REF_NAME==accumulator_design_smartconnect_0_0} -quiet] -quiet

# IP: bd/accumulator_design/ip/accumulator_design_xlconcat_0_0/accumulator_design_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accumulator_design_xlconcat_0_0 || ORIG_REF_NAME==accumulator_design_xlconcat_0_0} -quiet] -quiet

# IP: bd/accumulator_design/ip/accumulator_design_rst_ps7_0_50M_0/accumulator_design_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accumulator_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==accumulator_design_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/accumulator_design/ip/accumulator_design_auto_pc_0/accumulator_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accumulator_design_auto_pc_0 || ORIG_REF_NAME==accumulator_design_auto_pc_0} -quiet] -quiet

# IP: bd/accumulator_design/ip/accumulator_design_ps7_0_axi_periph_0/accumulator_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accumulator_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==accumulator_design_ps7_0_axi_periph_0} -quiet] -quiet

# XDC: bd/accumulator_design/accumulator_design_ooc.xdc
