# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/xlinx-projects/scu_timer_interrupts/scu_timer_interrupts.srcs/sources_1/bd/hw_3_p1/ip/hw_3_p1_processing_system7_0_0/hw_3_p1_processing_system7_0_0.xci
# IP: The module: 'hw_3_p1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/xlinx-projects/scu_timer_interrupts/scu_timer_interrupts.srcs/sources_1/bd/hw_3_p1/ip/hw_3_p1_processing_system7_0_0/hw_3_p1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_3_p1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/xlinx-projects/scu_timer_interrupts/scu_timer_interrupts.srcs/sources_1/bd/hw_3_p1/ip/hw_3_p1_processing_system7_0_0/hw_3_p1_processing_system7_0_0.xci
# IP: The module: 'hw_3_p1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/xlinx-projects/scu_timer_interrupts/scu_timer_interrupts.srcs/sources_1/bd/hw_3_p1/ip/hw_3_p1_processing_system7_0_0/hw_3_p1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_3_p1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
