# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/stream_fifo/stream_fifo.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==stream_fifo || ORIG_REF_NAME==stream_fifo} -quiet] -quiet

# IP: bd/stream_fifo/ip/stream_fifo_processing_system7_0_0/stream_fifo_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==stream_fifo_processing_system7_0_0 || ORIG_REF_NAME==stream_fifo_processing_system7_0_0} -quiet] -quiet

# IP: bd/stream_fifo/ip/stream_fifo_axi_fifo_mm_s_0_0/stream_fifo_axi_fifo_mm_s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==stream_fifo_axi_fifo_mm_s_0_0 || ORIG_REF_NAME==stream_fifo_axi_fifo_mm_s_0_0} -quiet] -quiet

# IP: bd/stream_fifo/ip/stream_fifo_ps7_0_axi_periph_0/stream_fifo_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==stream_fifo_ps7_0_axi_periph_0 || ORIG_REF_NAME==stream_fifo_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/stream_fifo/ip/stream_fifo_rst_ps7_0_50M_0/stream_fifo_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==stream_fifo_rst_ps7_0_50M_0 || ORIG_REF_NAME==stream_fifo_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/stream_fifo/ip/stream_fifo_auto_pc_0/stream_fifo_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==stream_fifo_auto_pc_0 || ORIG_REF_NAME==stream_fifo_auto_pc_0} -quiet] -quiet

# XDC: bd/stream_fifo/stream_fifo_ooc.xdc
