# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/xlinx-projects/digilent-xdc-master/digilent-xdc-master/Zybo-Z7-Master.xdc

# Block Designs: bd/audio_design/audio_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_design || ORIG_REF_NAME==audio_design} -quiet] -quiet

# IP: bd/audio_design/ip/audio_design_axi_i2s_adi_0_0/audio_design_axi_i2s_adi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_design_axi_i2s_adi_0_0 || ORIG_REF_NAME==audio_design_axi_i2s_adi_0_0} -quiet] -quiet

# IP: bd/audio_design/ip/audio_design_processing_system7_0_0/audio_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_design_processing_system7_0_0 || ORIG_REF_NAME==audio_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/audio_design/ip/audio_design_axi_gpio_0_0/audio_design_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_design_axi_gpio_0_0 || ORIG_REF_NAME==audio_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/audio_design/ip/audio_design_axi_gpio_0_1/audio_design_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_design_axi_gpio_0_1 || ORIG_REF_NAME==audio_design_axi_gpio_0_1} -quiet] -quiet

# IP: bd/audio_design/ip/audio_design_axi_gpio_0_2/audio_design_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_design_axi_gpio_0_2 || ORIG_REF_NAME==audio_design_axi_gpio_0_2} -quiet] -quiet

# IP: bd/audio_design/ip/audio_design_xbar_0/audio_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_design_xbar_0 || ORIG_REF_NAME==audio_design_xbar_0} -quiet] -quiet

# IP: bd/audio_design/ip/audio_design_ps7_0_axi_periph_0/audio_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==audio_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/audio_design/ip/audio_design_rst_ps7_0_100M_0/audio_design_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==audio_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/audio_design/ip/audio_design_auto_pc_0/audio_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==audio_design_auto_pc_0 || ORIG_REF_NAME==audio_design_auto_pc_0} -quiet] -quiet

# XDC: bd/audio_design/audio_design_ooc.xdc
