# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/xlinx-projects/floating_pt_accumulator/floating_pt_accumulator.srcs/sources_1/bd/accumulator_design/ip/accumulator_design_auto_pc_0/accumulator_design_auto_pc_0.xci
# IP: The module: 'accumulator_design_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/xlinx-projects/floating_pt_accumulator/floating_pt_accumulator.srcs/sources_1/bd/accumulator_design/ip/accumulator_design_auto_pc_0/accumulator_design_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'accumulator_design_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/xlinx-projects/floating_pt_accumulator/floating_pt_accumulator.srcs/sources_1/bd/accumulator_design/ip/accumulator_design_auto_pc_0/accumulator_design_auto_pc_0.xci
# IP: The module: 'accumulator_design_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/xlinx-projects/floating_pt_accumulator/floating_pt_accumulator.srcs/sources_1/bd/accumulator_design/ip/accumulator_design_auto_pc_0/accumulator_design_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'accumulator_design_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
