# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/xlinx-projects/dma_transfer_2/dma_transfer_2.srcs/sources_1/bd/dma_design/ip/dma_design_rst_ps7_0_50M_0/dma_design_rst_ps7_0_50M_0.xci
# IP: The module: 'dma_design_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/xlinx-projects/dma_transfer_2/dma_transfer_2.srcs/sources_1/bd/dma_design/ip/dma_design_rst_ps7_0_50M_0/dma_design_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/xlinx-projects/dma_transfer_2/dma_transfer_2.srcs/sources_1/bd/dma_design/ip/dma_design_rst_ps7_0_50M_0/dma_design_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/xlinx-projects/dma_transfer_2/dma_transfer_2.srcs/sources_1/bd/dma_design/ip/dma_design_rst_ps7_0_50M_0/dma_design_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/xlinx-projects/dma_transfer_2/dma_transfer_2.srcs/sources_1/bd/dma_design/ip/dma_design_rst_ps7_0_50M_0/dma_design_rst_ps7_0_50M_0.xci
# IP: The module: 'dma_design_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/xlinx-projects/dma_transfer_2/dma_transfer_2.srcs/sources_1/bd/dma_design/ip/dma_design_rst_ps7_0_50M_0/dma_design_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/xlinx-projects/dma_transfer_2/dma_transfer_2.srcs/sources_1/bd/dma_design/ip/dma_design_rst_ps7_0_50M_0/dma_design_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/xlinx-projects/dma_transfer_2/dma_transfer_2.srcs/sources_1/bd/dma_design/ip/dma_design_rst_ps7_0_50M_0/dma_design_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
