# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/knight_rider/knight_rider.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==knight_rider || ORIG_REF_NAME==knight_rider} -quiet] -quiet

# IP: bd/knight_rider/ip/knight_rider_axi_gpio_0_0/knight_rider_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==knight_rider_axi_gpio_0_0 || ORIG_REF_NAME==knight_rider_axi_gpio_0_0} -quiet] -quiet

# IP: bd/knight_rider/ip/knight_rider_axi_gpio_1_0/knight_rider_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==knight_rider_axi_gpio_1_0 || ORIG_REF_NAME==knight_rider_axi_gpio_1_0} -quiet] -quiet

# IP: bd/knight_rider/ip/knight_rider_xlconcat_0_0/knight_rider_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==knight_rider_xlconcat_0_0 || ORIG_REF_NAME==knight_rider_xlconcat_0_0} -quiet] -quiet

# IP: bd/knight_rider/ip/knight_rider_processing_system7_0_0/knight_rider_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==knight_rider_processing_system7_0_0 || ORIG_REF_NAME==knight_rider_processing_system7_0_0} -quiet] -quiet

# IP: bd/knight_rider/ip/knight_rider_xbar_0/knight_rider_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==knight_rider_xbar_0 || ORIG_REF_NAME==knight_rider_xbar_0} -quiet] -quiet

# IP: bd/knight_rider/ip/knight_rider_auto_pc_0/knight_rider_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==knight_rider_auto_pc_0 || ORIG_REF_NAME==knight_rider_auto_pc_0} -quiet] -quiet

# IP: bd/knight_rider/ip/knight_rider_ps7_0_axi_periph_0/knight_rider_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==knight_rider_ps7_0_axi_periph_0 || ORIG_REF_NAME==knight_rider_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/knight_rider/ip/knight_rider_rst_ps7_0_50M_0/knight_rider_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==knight_rider_rst_ps7_0_50M_0 || ORIG_REF_NAME==knight_rider_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/knight_rider/ip/knight_rider_axi_timer_0_0/knight_rider_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==knight_rider_axi_timer_0_0 || ORIG_REF_NAME==knight_rider_axi_timer_0_0} -quiet] -quiet

# XDC: bd/knight_rider/knight_rider_ooc.xdc
