# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/xlinx-projects/gpio_with_interrupt/gpio_with_interrupt.srcs/sources_1/bd/gpio_interrupt/ip/gpio_interrupt_axi_gpio_0_0/gpio_interrupt_axi_gpio_0_0.xci
# IP: The module: 'gpio_interrupt_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/xlinx-projects/gpio_with_interrupt/gpio_with_interrupt.srcs/sources_1/bd/gpio_interrupt/ip/gpio_interrupt_axi_gpio_0_0/gpio_interrupt_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'gpio_interrupt_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/xlinx-projects/gpio_with_interrupt/gpio_with_interrupt.srcs/sources_1/bd/gpio_interrupt/ip/gpio_interrupt_axi_gpio_0_0/gpio_interrupt_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gpio_interrupt_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/xlinx-projects/gpio_with_interrupt/gpio_with_interrupt.srcs/sources_1/bd/gpio_interrupt/ip/gpio_interrupt_axi_gpio_0_0/gpio_interrupt_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'gpio_interrupt_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/xlinx-projects/gpio_with_interrupt/gpio_with_interrupt.srcs/sources_1/bd/gpio_interrupt/ip/gpio_interrupt_axi_gpio_0_0/gpio_interrupt_axi_gpio_0_0.xci
# IP: The module: 'gpio_interrupt_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/xlinx-projects/gpio_with_interrupt/gpio_with_interrupt.srcs/sources_1/bd/gpio_interrupt/ip/gpio_interrupt_axi_gpio_0_0/gpio_interrupt_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'gpio_interrupt_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/xlinx-projects/gpio_with_interrupt/gpio_with_interrupt.srcs/sources_1/bd/gpio_interrupt/ip/gpio_interrupt_axi_gpio_0_0/gpio_interrupt_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gpio_interrupt_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/xlinx-projects/gpio_with_interrupt/gpio_with_interrupt.srcs/sources_1/bd/gpio_interrupt/ip/gpio_interrupt_axi_gpio_0_0/gpio_interrupt_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'gpio_interrupt_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
