# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/xlinx-projects/digilent-xdc-master/digilent-xdc-master/Zybo-Master.xdc

# Block Designs: bd/custo_ip_tb/custo_ip_tb.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custo_ip_tb || ORIG_REF_NAME==custo_ip_tb} -quiet] -quiet

# IP: bd/custo_ip_tb/ip/custo_ip_tb_led_driver_0_0/custo_ip_tb_led_driver_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custo_ip_tb_led_driver_0_0 || ORIG_REF_NAME==custo_ip_tb_led_driver_0_0} -quiet] -quiet

# IP: bd/custo_ip_tb/ip/custo_ip_tb_processing_system7_0_0/custo_ip_tb_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custo_ip_tb_processing_system7_0_0 || ORIG_REF_NAME==custo_ip_tb_processing_system7_0_0} -quiet] -quiet

# IP: bd/custo_ip_tb/ip/custo_ip_tb_ps7_0_axi_periph_0/custo_ip_tb_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custo_ip_tb_ps7_0_axi_periph_0 || ORIG_REF_NAME==custo_ip_tb_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/custo_ip_tb/ip/custo_ip_tb_rst_ps7_0_50M_0/custo_ip_tb_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custo_ip_tb_rst_ps7_0_50M_0 || ORIG_REF_NAME==custo_ip_tb_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/custo_ip_tb/ip/custo_ip_tb_xbar_0/custo_ip_tb_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custo_ip_tb_xbar_0 || ORIG_REF_NAME==custo_ip_tb_xbar_0} -quiet] -quiet

# IP: bd/custo_ip_tb/ip/custo_ip_tb_auto_pc_0/custo_ip_tb_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custo_ip_tb_auto_pc_0 || ORIG_REF_NAME==custo_ip_tb_auto_pc_0} -quiet] -quiet

# IP: bd/custo_ip_tb/ip/custo_ip_tb_axi_gpio_0_0/custo_ip_tb_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custo_ip_tb_axi_gpio_0_0 || ORIG_REF_NAME==custo_ip_tb_axi_gpio_0_0} -quiet] -quiet

# IP: bd/custo_ip_tb/ip/custo_ip_tb_axi_gpio_0_1/custo_ip_tb_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custo_ip_tb_axi_gpio_0_1 || ORIG_REF_NAME==custo_ip_tb_axi_gpio_0_1} -quiet] -quiet

# XDC: bd/custo_ip_tb/custo_ip_tb_ooc.xdc
