# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/xlinx-projects/digilent-xdc-master/digilent-xdc-master/Zybo-Z7-Master.xdc

# Block Designs: bd/knightrider_test_2/knightrider_test_2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==knightrider_test_2 || ORIG_REF_NAME==knightrider_test_2} -quiet] -quiet

# IP: bd/knightrider_test_2/ip/knightrider_test_2_knight_rd_ip_0_0/knightrider_test_2_knight_rd_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==knightrider_test_2_knight_rd_ip_0_0 || ORIG_REF_NAME==knightrider_test_2_knight_rd_ip_0_0} -quiet] -quiet

# IP: bd/knightrider_test_2/ip/knightrider_test_2_processing_system7_0_0/knightrider_test_2_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==knightrider_test_2_processing_system7_0_0 || ORIG_REF_NAME==knightrider_test_2_processing_system7_0_0} -quiet] -quiet

# IP: bd/knightrider_test_2/ip/knightrider_test_2_auto_pc_0/knightrider_test_2_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==knightrider_test_2_auto_pc_0 || ORIG_REF_NAME==knightrider_test_2_auto_pc_0} -quiet] -quiet

# IP: bd/knightrider_test_2/ip/knightrider_test_2_ps7_0_axi_periph_0/knightrider_test_2_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==knightrider_test_2_ps7_0_axi_periph_0 || ORIG_REF_NAME==knightrider_test_2_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/knightrider_test_2/ip/knightrider_test_2_rst_ps7_0_50M_0/knightrider_test_2_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==knightrider_test_2_rst_ps7_0_50M_0 || ORIG_REF_NAME==knightrider_test_2_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: bd/knightrider_test_2/knightrider_test_2_ooc.xdc
