# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/stopwatch/stopwatch.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==stopwatch || ORIG_REF_NAME==stopwatch} -quiet] -quiet

# IP: bd/stopwatch/ip/stopwatch_processing_system7_0_0/stopwatch_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==stopwatch_processing_system7_0_0 || ORIG_REF_NAME==stopwatch_processing_system7_0_0} -quiet] -quiet

# IP: bd/stopwatch/ip/stopwatch_axi_timer_0_0/stopwatch_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==stopwatch_axi_timer_0_0 || ORIG_REF_NAME==stopwatch_axi_timer_0_0} -quiet] -quiet

# IP: bd/stopwatch/ip/stopwatch_axi_gpio_0_0/stopwatch_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==stopwatch_axi_gpio_0_0 || ORIG_REF_NAME==stopwatch_axi_gpio_0_0} -quiet] -quiet

# IP: bd/stopwatch/ip/stopwatch_xlconcat_0_0/stopwatch_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==stopwatch_xlconcat_0_0 || ORIG_REF_NAME==stopwatch_xlconcat_0_0} -quiet] -quiet

# IP: bd/stopwatch/ip/stopwatch_xbar_0/stopwatch_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==stopwatch_xbar_0 || ORIG_REF_NAME==stopwatch_xbar_0} -quiet] -quiet

# IP: bd/stopwatch/ip/stopwatch_auto_pc_0/stopwatch_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==stopwatch_auto_pc_0 || ORIG_REF_NAME==stopwatch_auto_pc_0} -quiet] -quiet

# IP: bd/stopwatch/ip/stopwatch_ps7_0_axi_periph_0/stopwatch_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==stopwatch_ps7_0_axi_periph_0 || ORIG_REF_NAME==stopwatch_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/stopwatch/ip/stopwatch_rst_ps7_0_50M_0/stopwatch_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==stopwatch_rst_ps7_0_50M_0 || ORIG_REF_NAME==stopwatch_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: bd/stopwatch/stopwatch_ooc.xdc
