# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/blinking_led_design/blinking_led_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blinking_led_design || ORIG_REF_NAME==blinking_led_design} -quiet] -quiet

# IP: bd/blinking_led_design/ip/blinking_led_design_axi_gpio_0_0/blinking_led_design_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blinking_led_design_axi_gpio_0_0 || ORIG_REF_NAME==blinking_led_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/blinking_led_design/ip/blinking_led_design_axi_gpio_0_1/blinking_led_design_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blinking_led_design_axi_gpio_0_1 || ORIG_REF_NAME==blinking_led_design_axi_gpio_0_1} -quiet] -quiet

# IP: bd/blinking_led_design/ip/blinking_led_design_axi_timer_0_0/blinking_led_design_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blinking_led_design_axi_timer_0_0 || ORIG_REF_NAME==blinking_led_design_axi_timer_0_0} -quiet] -quiet

# IP: bd/blinking_led_design/ip/blinking_led_design_xlconcat_0_0/blinking_led_design_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blinking_led_design_xlconcat_0_0 || ORIG_REF_NAME==blinking_led_design_xlconcat_0_0} -quiet] -quiet

# IP: bd/blinking_led_design/ip/blinking_led_design_processing_system7_0_0/blinking_led_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blinking_led_design_processing_system7_0_0 || ORIG_REF_NAME==blinking_led_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/blinking_led_design/ip/blinking_led_design_xbar_0/blinking_led_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blinking_led_design_xbar_0 || ORIG_REF_NAME==blinking_led_design_xbar_0} -quiet] -quiet

# IP: bd/blinking_led_design/ip/blinking_led_design_auto_pc_0/blinking_led_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blinking_led_design_auto_pc_0 || ORIG_REF_NAME==blinking_led_design_auto_pc_0} -quiet] -quiet

# IP: bd/blinking_led_design/ip/blinking_led_design_ps7_0_axi_periph_0/blinking_led_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blinking_led_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==blinking_led_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/blinking_led_design/ip/blinking_led_design_rst_ps7_0_50M_0/blinking_led_design_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blinking_led_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==blinking_led_design_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: bd/blinking_led_design/blinking_led_design_ooc.xdc
