# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/sws_diagram/sws_diagram.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sws_diagram || ORIG_REF_NAME==sws_diagram} -quiet] -quiet

# IP: bd/sws_diagram/ip/sws_diagram_axi_gpio_0_0/sws_diagram_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sws_diagram_axi_gpio_0_0 || ORIG_REF_NAME==sws_diagram_axi_gpio_0_0} -quiet] -quiet

# IP: bd/sws_diagram/ip/sws_diagram_processing_system7_0_0/sws_diagram_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sws_diagram_processing_system7_0_0 || ORIG_REF_NAME==sws_diagram_processing_system7_0_0} -quiet] -quiet

# IP: bd/sws_diagram/ip/sws_diagram_ps7_0_axi_periph_0/sws_diagram_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sws_diagram_ps7_0_axi_periph_0 || ORIG_REF_NAME==sws_diagram_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/sws_diagram/ip/sws_diagram_rst_ps7_0_50M_0/sws_diagram_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sws_diagram_rst_ps7_0_50M_0 || ORIG_REF_NAME==sws_diagram_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/sws_diagram/ip/sws_diagram_auto_pc_0/sws_diagram_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sws_diagram_auto_pc_0 || ORIG_REF_NAME==sws_diagram_auto_pc_0} -quiet] -quiet

# XDC: bd/sws_diagram/sws_diagram_ooc.xdc
