# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/hw_3_p1/hw_3_p1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_3_p1 || ORIG_REF_NAME==hw_3_p1} -quiet] -quiet

# IP: bd/hw_3_p1/ip/hw_3_p1_processing_system7_0_0/hw_3_p1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_3_p1_processing_system7_0_0 || ORIG_REF_NAME==hw_3_p1_processing_system7_0_0} -quiet] -quiet

# IP: bd/hw_3_p1/ip/hw_3_p1_axi_gpio_0_0/hw_3_p1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_3_p1_axi_gpio_0_0 || ORIG_REF_NAME==hw_3_p1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/hw_3_p1/ip/hw_3_p1_axi_gpio_0_1/hw_3_p1_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_3_p1_axi_gpio_0_1 || ORIG_REF_NAME==hw_3_p1_axi_gpio_0_1} -quiet] -quiet

# IP: bd/hw_3_p1/ip/hw_3_p1_xbar_0/hw_3_p1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_3_p1_xbar_0 || ORIG_REF_NAME==hw_3_p1_xbar_0} -quiet] -quiet

# IP: bd/hw_3_p1/ip/hw_3_p1_auto_pc_0/hw_3_p1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_3_p1_auto_pc_0 || ORIG_REF_NAME==hw_3_p1_auto_pc_0} -quiet] -quiet

# IP: bd/hw_3_p1/ip/hw_3_p1_ps7_0_axi_periph_0/hw_3_p1_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_3_p1_ps7_0_axi_periph_0 || ORIG_REF_NAME==hw_3_p1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/hw_3_p1/ip/hw_3_p1_rst_ps7_0_50M_0/hw_3_p1_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_3_p1_rst_ps7_0_50M_0 || ORIG_REF_NAME==hw_3_p1_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: bd/hw_3_p1/hw_3_p1_ooc.xdc
