# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/xlinx-projects/knightrider_ip/knight_rd_tb/knight_rd_tb.srcs/sources_1/bd/knightrider_test_2/ip/knightrider_test_2_auto_pc_0/knightrider_test_2_auto_pc_0.xci
# IP: The module: 'knightrider_test_2_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/xlinx-projects/knightrider_ip/knight_rd_tb/knight_rd_tb.srcs/sources_1/bd/knightrider_test_2/ip/knightrider_test_2_auto_pc_0/knightrider_test_2_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'knightrider_test_2_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/xlinx-projects/knightrider_ip/knight_rd_tb/knight_rd_tb.srcs/sources_1/bd/knightrider_test_2/ip/knightrider_test_2_auto_pc_0/knightrider_test_2_auto_pc_0.xci
# IP: The module: 'knightrider_test_2_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/xlinx-projects/knightrider_ip/knight_rd_tb/knight_rd_tb.srcs/sources_1/bd/knightrider_test_2/ip/knightrider_test_2_auto_pc_0/knightrider_test_2_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'knightrider_test_2_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
