# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/xlinx-projects/digilent-xdc-master/digilent-xdc-master/Zybo-Z7-Master.xdc

# Block Designs: bd/kn_rd_tb/kn_rd_tb.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kn_rd_tb || ORIG_REF_NAME==kn_rd_tb} -quiet] -quiet

# IP: bd/kn_rd_tb/ip/kn_rd_tb_kn_rd_0_0/kn_rd_tb_kn_rd_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kn_rd_tb_kn_rd_0_0 || ORIG_REF_NAME==kn_rd_tb_kn_rd_0_0} -quiet] -quiet

# IP: bd/kn_rd_tb/ip/kn_rd_tb_processing_system7_0_0/kn_rd_tb_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kn_rd_tb_processing_system7_0_0 || ORIG_REF_NAME==kn_rd_tb_processing_system7_0_0} -quiet] -quiet

# IP: bd/kn_rd_tb/ip/kn_rd_tb_ps7_0_axi_periph_0/kn_rd_tb_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kn_rd_tb_ps7_0_axi_periph_0 || ORIG_REF_NAME==kn_rd_tb_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/kn_rd_tb/ip/kn_rd_tb_rst_ps7_0_50M_0/kn_rd_tb_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kn_rd_tb_rst_ps7_0_50M_0 || ORIG_REF_NAME==kn_rd_tb_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/kn_rd_tb/ip/kn_rd_tb_auto_pc_0/kn_rd_tb_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kn_rd_tb_auto_pc_0 || ORIG_REF_NAME==kn_rd_tb_auto_pc_0} -quiet] -quiet

# XDC: bd/kn_rd_tb/kn_rd_tb_ooc.xdc
