# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/scutimer/scutimer.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==scutimer || ORIG_REF_NAME==scutimer} -quiet] -quiet

# IP: bd/scutimer/ip/scutimer_processing_system7_0_0/scutimer_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==scutimer_processing_system7_0_0 || ORIG_REF_NAME==scutimer_processing_system7_0_0} -quiet] -quiet

# XDC: bd/scutimer/scutimer_ooc.xdc
