# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/dma_design/dma_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_design || ORIG_REF_NAME==dma_design} -quiet] -quiet

# IP: bd/dma_design/ip/dma_design_processing_system7_0_1/dma_design_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_design_processing_system7_0_1 || ORIG_REF_NAME==dma_design_processing_system7_0_1} -quiet] -quiet

# IP: bd/dma_design/ip/dma_design_axi_dma_0_1/dma_design_axi_dma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_design_axi_dma_0_1 || ORIG_REF_NAME==dma_design_axi_dma_0_1} -quiet] -quiet

# IP: bd/dma_design/ip/dma_design_xlconcat_0_1/dma_design_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_design_xlconcat_0_1 || ORIG_REF_NAME==dma_design_xlconcat_0_1} -quiet] -quiet

# IP: bd/dma_design/ip/dma_design_floating_point_0_1/dma_design_floating_point_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_design_floating_point_0_1 || ORIG_REF_NAME==dma_design_floating_point_0_1} -quiet] -quiet

# IP: bd/dma_design/ip/dma_design_smartconnect_0_0/dma_design_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_design_smartconnect_0_0 || ORIG_REF_NAME==dma_design_smartconnect_0_0} -quiet] -quiet

# IP: bd/dma_design/ip/dma_design_ps7_0_axi_periph_3/dma_design_ps7_0_axi_periph_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_design_ps7_0_axi_periph_3 || ORIG_REF_NAME==dma_design_ps7_0_axi_periph_3} -quiet] -quiet

# IP: bd/dma_design/ip/dma_design_rst_ps7_0_50M_3/dma_design_rst_ps7_0_50M_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_design_rst_ps7_0_50M_3 || ORIG_REF_NAME==dma_design_rst_ps7_0_50M_3} -quiet] -quiet

# IP: bd/dma_design/ip/dma_design_auto_pc_0/dma_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_design_auto_pc_0 || ORIG_REF_NAME==dma_design_auto_pc_0} -quiet] -quiet

# XDC: bd/dma_design/dma_design_ooc.xdc
