# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/xlinx-projects/dma_transfer/dma_transfer.srcs/sources_1/bd/dma_design/ip/dma_design_processing_system7_0_1/dma_design_processing_system7_0_1.xci
# IP: The module: 'dma_design_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/xlinx-projects/dma_transfer/dma_transfer.srcs/sources_1/bd/dma_design/ip/dma_design_processing_system7_0_1/dma_design_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_design_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/xlinx-projects/dma_transfer/dma_transfer.srcs/sources_1/bd/dma_design/ip/dma_design_processing_system7_0_1/dma_design_processing_system7_0_1.xci
# IP: The module: 'dma_design_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/xlinx-projects/dma_transfer/dma_transfer.srcs/sources_1/bd/dma_design/ip/dma_design_processing_system7_0_1/dma_design_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_design_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
