# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/xlinx-projects/knight_rider/knight_rider.srcs/sources_1/bd/knight_rider/ip/knight_rider_auto_pc_0/knight_rider_auto_pc_0.xci
# IP: The module: 'knight_rider_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/xlinx-projects/knight_rider/knight_rider.srcs/sources_1/bd/knight_rider/ip/knight_rider_auto_pc_0/knight_rider_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'knight_rider_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/xlinx-projects/knight_rider/knight_rider.srcs/sources_1/bd/knight_rider/ip/knight_rider_auto_pc_0/knight_rider_auto_pc_0.xci
# IP: The module: 'knight_rider_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/xlinx-projects/knight_rider/knight_rider.srcs/sources_1/bd/knight_rider/ip/knight_rider_auto_pc_0/knight_rider_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'knight_rider_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
