# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/gpio_interrupt/gpio_interrupt.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpio_interrupt || ORIG_REF_NAME==gpio_interrupt} -quiet] -quiet

# IP: bd/gpio_interrupt/ip/gpio_interrupt_axi_gpio_0_0/gpio_interrupt_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpio_interrupt_axi_gpio_0_0 || ORIG_REF_NAME==gpio_interrupt_axi_gpio_0_0} -quiet] -quiet

# IP: bd/gpio_interrupt/ip/gpio_interrupt_axi_gpio_1_0/gpio_interrupt_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpio_interrupt_axi_gpio_1_0 || ORIG_REF_NAME==gpio_interrupt_axi_gpio_1_0} -quiet] -quiet

# IP: bd/gpio_interrupt/ip/gpio_interrupt_processing_system7_0_0/gpio_interrupt_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpio_interrupt_processing_system7_0_0 || ORIG_REF_NAME==gpio_interrupt_processing_system7_0_0} -quiet] -quiet

# IP: bd/gpio_interrupt/ip/gpio_interrupt_xbar_0/gpio_interrupt_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpio_interrupt_xbar_0 || ORIG_REF_NAME==gpio_interrupt_xbar_0} -quiet] -quiet

# IP: bd/gpio_interrupt/ip/gpio_interrupt_auto_pc_0/gpio_interrupt_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpio_interrupt_auto_pc_0 || ORIG_REF_NAME==gpio_interrupt_auto_pc_0} -quiet] -quiet

# IP: bd/gpio_interrupt/ip/gpio_interrupt_ps7_0_axi_periph_0/gpio_interrupt_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpio_interrupt_ps7_0_axi_periph_0 || ORIG_REF_NAME==gpio_interrupt_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/gpio_interrupt/ip/gpio_interrupt_rst_ps7_0_50M_0/gpio_interrupt_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpio_interrupt_rst_ps7_0_50M_0 || ORIG_REF_NAME==gpio_interrupt_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: bd/gpio_interrupt/gpio_interrupt_ooc.xdc
