# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/xlinx-projects/final_p1/final_p1.srcs/sources_1/bd/sws_diagram/ip/sws_diagram_auto_pc_0/sws_diagram_auto_pc_0.xci
# IP: The module: 'sws_diagram_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/xlinx-projects/final_p1/final_p1.srcs/sources_1/bd/sws_diagram/ip/sws_diagram_auto_pc_0/sws_diagram_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sws_diagram_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/xlinx-projects/final_p1/final_p1.srcs/sources_1/bd/sws_diagram/ip/sws_diagram_auto_pc_0/sws_diagram_auto_pc_0.xci
# IP: The module: 'sws_diagram_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/xlinx-projects/final_p1/final_p1.srcs/sources_1/bd/sws_diagram/ip/sws_diagram_auto_pc_0/sws_diagram_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sws_diagram_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
